#!/usr/bin/env node
/**
 * Script to generate TypeScript types from backend OpenAPI/Swagger spec
 * 
 * This script:
 * 1. Fetches the OpenAPI spec from the backend
 * 2. Generates TypeScript types using openapi-typescript
 * 3. Outputs to src/types/generated/api.ts
 * 4. Generates enums.ts with extracted enum types
 */

import { writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import openapiTS from 'openapi-typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Get API base URL from environment or use default
const API_BASE_URL = process.env.VITE_API_BASE_URL || 'http://localhost:5001';
const SWAGGER_URL = `${API_BASE_URL}/swagger/v1/swagger.json`;
const OUTPUT_FILE = join(__dirname, '../src/types/generated/api.ts');
const ENUMS_FILE = join(__dirname, '../src/types/generated/enums.ts');

/**
 * Generate enums.ts file with all enum types extracted from the API spec
 * and additional types based on backend constants
 */
function generateEnumsFile() {
  const enumsContent = `/**
 * Enum types extracted from the generated OpenAPI types
 * 
 * This file re-exports enum types from the generated API types
 * to provide a cleaner interface for use throughout the application.
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it should be regenerated from the API spec.
 * 
 * Note: Since the backend serializes enums as strings, the generated types
 * use string types. We define explicit string literal unions here that match
 * the backend enum values to ensure type safety.
 */

import type { components } from './api';

// Extract enum types from generated components where they are explicitly defined
export type GlobalRole = NonNullable<
  components['schemas']['IntelliPM.Application.Organizations.Commands.UpdateUserGlobalRoleResponse']['globalRole']
>;

export type ProjectRole = NonNullable<
  components['schemas']['IntelliPM.Application.Projects.Queries.ProjectMemberDto']['role']
>;

// Status types - these match the backend enum values
// Backend serializes enums as strings, so we define string literal unions

export type ProjectStatus = 
  | 'Active' 
  | 'OnHold' 
  | 'Completed' 
  | 'Archived';

export type SprintStatus = 
  | 'Planned' 
  | 'Active' 
  | 'Completed';

export type TaskStatus = 
  | 'Todo' 
  | 'InProgress' 
  | 'Blocked' 
  | 'Done';

export type DefectStatus = 
  | 'Open' 
  | 'InProgress' 
  | 'Resolved' 
  | 'Closed';

export type DefectSeverity = 
  | 'Low' 
  | 'Medium' 
  | 'High' 
  | 'Critical';

export type TaskPriority = 
  | 'Low' 
  | 'Medium' 
  | 'High' 
  | 'Critical';

export type ProjectType = 
  | 'Scrum' 
  | 'Kanban' 
  | 'Waterfall';

// Release types (from backend ReleaseStatus, ReleaseType enums)
export type ReleaseStatus = 
  | 'Planned'
  | 'InProgress'
  | 'Testing'
  | 'ReadyForDeployment'
  | 'Deployed'
  | 'Failed'
  | 'Cancelled';

export type ReleaseType = 
  | 'Major'
  | 'Minor'
  | 'Patch'
  | 'Hotfix';

// Quality Gate types
export type QualityGateStatus = 
  | 'Passed'
  | 'Warning'
  | 'Failed'
  | 'Pending'
  | 'Skipped';

export type QualityGateType = 
  | 'CodeCoverage'
  | 'AllTasksCompleted'
  | 'NoOpenBugs'
  | 'CodeReviewApproval'
  | 'SecurityScan'
  | 'PerformanceTests'
  | 'DocumentationComplete'
  | 'ManualApproval';

// Milestone types
export type MilestoneType = 
  | 'Release'
  | 'Sprint'
  | 'Deadline'
  | 'Custom';

export type MilestoneStatus = 
  | 'Pending'
  | 'InProgress'
  | 'Completed'
  | 'Missed'
  | 'Cancelled';

// Dependency types
export type DependencyType = 
  | 'FinishToStart'
  | 'StartToStart'
  | 'FinishToFinish'
  | 'StartToFinish';

// Notification types (from backend NotificationConstants.Types)
export type NotificationType = 
  | 'TaskAssigned'
  | 'TaskStatusChanged'
  | 'TaskCommented'
  | 'Mentioned'
  | 'ProjectInvite'
  | 'SprintStarted'
  | 'SprintCompleted'
  | 'DefectReported'
  | 'DeadlineApproaching';

// Notification frequency types (from backend NotificationConstants.Frequencies)
export type NotificationFrequency = 
  | 'Instant'
  | 'Daily'
  | 'Weekly'
  | 'Never';

// AI Decision types (from backend AIDecisionConstants.DecisionTypes)
export type AIDecisionType = 
  | 'RiskDetection'
  | 'SprintPlanning'
  | 'TaskPrioritization'
  | 'BacklogPrioritization'
  | 'DeliveryAnalysis'
  | 'ExecutiveSummary'
  | 'QualityAnalysis'
  | 'BusinessValueAnalysis'
  | 'ResourceAllocation'
  | 'DeadlineEstimation'
  | 'CodeReview'
  | 'TestCoverage'
  | 'PerformanceAnalysis'
  | 'TaskImprovement'
  | 'ProjectAnalysis'
  | 'DependencyAnalysis'
  | 'SprintRetrospective';

// AI Agent types (from backend AIDecisionConstants.AgentTypes)
export type AIAgentType = 
  | 'ProductAgent'
  | 'DeliveryAgent'
  | 'ManagerAgent'
  | 'QAAgent'
  | 'BusinessAgent';

// AI Decision Status (from backend AIDecisionStatus enum)
export type AIDecisionStatus = 
  | 'Pending'
  | 'Approved'
  | 'Rejected'
  | 'Applied'
  | 'Expired'
  | 'PendingApproval'
  | 'Overridden';

// Re-export the components type for direct access if needed
export type { components } from './api';
`;

  writeFileSync(ENUMS_FILE, enumsContent, 'utf-8');
  console.log(`✅ Enums file generated successfully to ${ENUMS_FILE}`);
}

async function generateTypes() {
  try {
    console.log(`Fetching OpenAPI spec from ${SWAGGER_URL}...`);
    
    console.log('Generating TypeScript types...');
    // openapi-typescript can accept a URL directly
    const types = await openapiTS(SWAGGER_URL);
    
    // Write the generated types to file
    // types is a string, so we can write it directly
    writeFileSync(OUTPUT_FILE, types as string, 'utf-8');
    
    console.log(`✅ Types generated successfully to ${OUTPUT_FILE}`);
    console.log(`   Total size: ${((types as string).length / 1024).toFixed(2)} KB`);
    
    // Generate enums file
    console.log('Generating enums file...');
    generateEnumsFile();
    
    console.log('✅ Type generation completed successfully!');
    
  } catch (error) {
    console.error('❌ Error generating types:', error);
    if (error instanceof Error && error.message.includes('fetch')) {
      console.error('\n💡 Make sure the backend API is running at', SWAGGER_URL);
      console.error('   You can start it with: cd backend/IntelliPM.API && dotnet run');
    }
    process.exit(1);
  }
}

generateTypes();

