namespace IntelliPM.Application.Agents.DTOs;

/// <summary>
/// DTO for sprint retrospective generated by the AI agent.
/// </summary>
public class SprintRetrospectiveDto
{
    /// <summary>
    /// Sprint ID.
    /// </summary>
    public int SprintId { get; set; }

    /// <summary>
    /// Overall sprint summary.
    /// </summary>
    public string Summary { get; set; } = string.Empty;

    /// <summary>
    /// List of positive achievements ("what went well").
    /// </summary>
    public List<string> WhatWentWell { get; set; } = new();

    /// <summary>
    /// List of areas for improvement ("what could improve").
    /// </summary>
    public List<string> WhatCouldImprove { get; set; } = new();

    /// <summary>
    /// List of action items for the next sprint.
    /// </summary>
    public List<ActionItemDto> ActionItems { get; set; } = new();

    /// <summary>
    /// Sprint metrics.
    /// </summary>
    public RetrospectiveMetricsDto Metrics { get; set; } = new();

    /// <summary>
    /// Team performance analysis.
    /// </summary>
    public TeamPerformanceDto TeamPerformance { get; set; } = new();

    /// <summary>
    /// Recommendations for the next sprint.
    /// </summary>
    public List<string> Recommendations { get; set; } = new();
}

/// <summary>
/// DTO for an action item in the retrospective.
/// </summary>
public class ActionItemDto
{
    /// <summary>
    /// Action description.
    /// </summary>
    public string Action { get; set; } = string.Empty;

    /// <summary>
    /// Priority level: "low", "medium", "high".
    /// </summary>
    public string Priority { get; set; } = "medium";

    /// <summary>
    /// Owner of the action item (team member name or "team").
    /// </summary>
    public string Owner { get; set; } = "team";
}

/// <summary>
/// DTO for retrospective metrics.
/// </summary>
public class RetrospectiveMetricsDto
{
    /// <summary>
    /// Planned story points for the sprint.
    /// </summary>
    public int PlannedStoryPoints { get; set; }

    /// <summary>
    /// Completed story points.
    /// </summary>
    public int CompletedStoryPoints { get; set; }

    /// <summary>
    /// Velocity change compared to previous sprint (e.g., "+5%" or "-10%").
    /// </summary>
    public string? VelocityChange { get; set; }

    /// <summary>
    /// Number of defects discovered during the sprint.
    /// </summary>
    public int DefectCount { get; set; }

    /// <summary>
    /// Completion rate (0.0 to 1.0).
    /// </summary>
    public decimal CompletionRate { get; set; }
}

/// <summary>
/// DTO for team performance analysis.
/// </summary>
public class TeamPerformanceDto
{
    /// <summary>
    /// Engagement level: "low", "medium", "high".
    /// </summary>
    public string Engagement { get; set; } = "medium";

    /// <summary>
    /// List of identified bottlenecks.
    /// </summary>
    public List<string> Bottlenecks { get; set; } = new();

    /// <summary>
    /// List of team strengths.
    /// </summary>
    public List<string> Strengths { get; set; } = new();
}

